# This file defines service's detail. 
# See https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ecs/create-service.html 
# and https://pipecd.dev/docs/user-guide/configuration-reference/#restrictions-of-service-definition for other options.
cluster: arn:aws:ecs:ap-northeast-1:061293269148:cluster/pipecd-cluster # [EDIT_HERE] the cluster to which you deploy this service
serviceName: pipecd-tutorial-simple
desiredCount: 2
deploymentConfiguration:
  maximumPercent: 200
  minimumHealthyPercent: 0
schedulingStrategy: REPLICA
deploymentController:
  type: EXTERNAL # This must be EXTERNAL.
enableECSManagedTags: true
propagateTags: SERVICE
launchType: FARGATE
networkConfiguration:
  awsvpcConfiguration:
    assignPublicIp: ENABLED
    securityGroups:
      - sg-081ebf4828ee24c5e # [EDIT_HERE] The IDs of the security groups associated with the service. like sg-xxx
    subnets:
      - subnet-0f4bf4537a721a279 # [EDIT_HERE] The IDs of the subnets associated with the service. like subnet-xxx
      - subnet-0b398df153beeb2f4 # [EDIT_HERE] 