apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipecd-tutorial-simple
  labels:
    app: pipecd-tutorial-simple
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pipecd-tutorial-simple
      pipecd.dev/variant: primary
  template:
    metadata:
      labels:
        app: pipecd-tutorial-simple
        pipecd.dev/variant: primary
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: helloworld
        image: ghcr.io/pipe-cd/helloworld:v0.32.0
        args:
          - server
        ports:
        - containerPort: 9085