# This file defines the behavior of deploying a Lambda application with Canary strategy.
apiVersion: pipecd.dev/v1beta1
kind: LambdaApp
spec:
  name: canary-app
  input:
    functionManifestFile: function.yaml
  pipeline:
    stages:
      # Deploy workloads of the new version but it will receive no traffic yet.
      - name: LAMBDA_CANARY_ROLLOUT
      # Promote new version to receive traffic.
      - name: LAMBDA_PROMOTE
        with:
          percent: 10
      - name: WAIT
        with:
          duration: 30s
      - name: LAMBDA_PROMOTE
        with:
          percent: 50
      - name: WAIT
        with:
          duration: 30s
      # Promote new version to receive all traffic.
      - name: LAMBDA_PROMOTE
        with:
          percent: 100
  description: |
    This app demonstrates how to deploy a Lambda application with a customized pipeline.\
    The app will be deployed gradually.\
    cf.: [adding a new app](https://pipecd.dev/docs/user-guide/managing-application/adding-an-application/), [app configuration](https://pipecd.dev/docs/user-guide/configuration-reference/#lambda-application)