# This is a configuration for running a Control Plane. See https://pipecd.dev/docs/user-guide/managing-controlplane/configuration-reference/ for details.
apiVersion: "pipecd.dev/v1beta1"
kind: ControlPlane
spec:
  datastore:
    type: MYSQL
    config:
      url: root:test@tcp(pipecd-mysql:3306)
      database: tutorial
  filestore:
    type: MINIO
    config:
      endpoint: http://pipecd-minio:9000
      bucket: tutorial
      accessKeyFile: /etc/pipecd-secret/minio-access-key
      secretKeyFile: /etc/pipecd-secret/minio-secret-key
      autoCreateBucket: true
  projects:
    # This is a debugging project. See https://pipecd.dev/docs/user-guide/managing-controlplane/adding-a-project/ when using more features about projects.
    - id: tutorial
      staticAdmin:
        username: hello-pipecd
        passwordHash: "$2a$10$ye96mUqUqTnjUqgwQJbJzel/LJibRhUnmzyypACkvrTSnQpVFZ7qK" # bcrypt value of "hello-pipecd"
