apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipecd-tutorial-canary
  labels:
    app: pipecd-tutorial-canary
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: pipecd-tutorial-canary
      pipecd.dev/variant: primary
  template:
    metadata:
      labels:
        app: pipecd-tutorial-canary
        pipecd.dev/variant: primary
    spec:
      containers:
      - name: helloworld
        image: ghcr.io/pipe-cd/helloworld:v0.32.0
        args:
          - server
        ports:
        - containerPort: 9085